config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments, only: %i[create]

    member do
      patch :like, to: 'posts#like'
    end
  end

  get 'home/projects'
  get 'projects', to: 'projects#index', as: :projects
  get 'projects/chores_app'
  get 'projects/picu'
  get 'projects/portfolio'
  get 'projects/vision'
  get 'projects/christmas_bomb'


  get 'home/about'
  get 'home/contact'
  get 'resume', to: 'home#resume', as: :resume
  get 'home/download_resume'
  get 'blog', to: 'posts#index', as: :blog

  root 'home#landing'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :post

  validates_presence_of %i[name body]

  after_create_commit { broadcast_prepend_to [post, :comments], target: "#{dom_id(post)}_comments" }
end

app/models/like.rb
# frozen_string_literal: true

# Model for a Post's likes
class Like < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates_presence_of %i[title heading]

  has_rich_text :content

  def liked_by?(ip_address)
    likes.where(ip_address: ip_address).present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules
  devise :database_authenticatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :turbo_frame_request_variant
  before_action :set_ip_address

  private

  def turbo_frame_request_variant
    request.variant = :turbo_frame if turbo_frame_request?
  end

  def set_ip_address
    @ip_address = request.remote_ip
  end

  # If a non-authorized user tries to do something they shouldn't, send them
  # back to the root path
  def user_not_authorized
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.turbo_stream
        format.html { render partial: 'comments/form', locals: { comment: Comment.new }}
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('comment_form', partial: 'comments/form', locals: { comment: @comment }) }
        format.html { render partial: 'comments/form', locals: { comment: @comment }}
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :name)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Controller for all static pages
class HomeController < ApplicationController
  def landing
  end

  def work
  end

  def projects
  end

  def about
  end

  def contact
  end

  def resume
  end

  def download_resume
    resume = render_to_string "home/_resume_body", layout: "pdf"
    binary_pdf = Dhalang::PDF.get_from_html(resume)
    send_data(binary_pdf, filename: 'chris_clifton_resume.pdf', type: 'application/pdf') 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :set_post, only: %i[ show edit update destroy like]

  # GET /posts or /posts.json
  def index
    if params[:query].present?
      @posts = Post.where("LOWER(title) LIKE ?", "%#{params[:query].downcase}%").order(created_at: :desc)
    else
      @posts = Post.all.order(created_at: :desc)
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    authorize @post
  end

  # GET /posts/1/edit
  def edit
    authorize @post
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    authorize @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    authorize @post

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    authorize @post

    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def like
    if @post.liked_by?(@ip_address)
      @post.likes.where(ip_address: @ip_address).first.destroy
    else
      Like.create!(post_id: @post.id, ip_address: @ip_address)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "#{dom_id(@post)}_likes",
          partial: 'posts/likes',
          locals: { post: @post }
        )
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :heading, :content)
    end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  def index
  end

  def chores_app
  end

  def picu
  end

  def portfolio
  end

  def vision
  end

  def christmas_bomb
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_nav(view_title, action_name, controller_name)
    if controller_name == 'home'
      if view_title == action_name
        'active-nav-element'
      else
        'nav-element'
      end
    else
      if view_title == controller_name
        'active-nav-element'
      else
        'nav-element'
      end
    end
  end

  def active_mobile_nav(view_title, action_name, controller_name)
    if controller_name == 'home'
      if view_title == action_name
        'active-mobile-nav-element'
      else
        'mobile-nav-element'
      end
    else
      if view_title == controller_name
        'active-mobile-nav-element'
      else
        'mobile-nav-element'
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= turbo_frame_tag "comment_form" do %>
  <%= form_with model: comment, url: post_comments_path(@post) do |form| %>
    <div class="text-2xl my-4">
      Comments
    </div>
    <div class="pb-4">
      If you have any questions, comments, or feedback, please leave them below!
    </div>
    <% if comment.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
          <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="pb-4">
      <%= form.label :name, class: "label" %>
      <%= form.text_field :name, class: "input md:w-3/4" %>
    </div>

    <div class="pb-4">
      <%= form.label :body, class: "label" %>
      <%= form.text_area :body, rows: 5, class: "input md:w-3/4" %>
    </div>

    <%= form.submit 'Submit', class: "mb-4 rounded-lg py-3 px-5 bg-indigo-600 text-white inline-block font-medium cursor-pointer" %>
  <% end %>
<% end %>

app/views/home/landing.html.erb
<div class="relative bg-white overflow-hidden">
  <div class="max-w-7xl mx-auto">
    <div class="relative z-10 pb-8 bg-white sm:pb-16 md:pb-20 lg:max-w-2xl lg:w-full lg:pb-28 xl:pb-32">
      <svg class="hidden lg:block absolute right-0 inset-y-0 h-full w-48 text-white transform translate-x-1/2" fill="currentColor" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">
        <polygon points="50,0 100,0 50,100 0,100" />
      </svg>

      <div>
        <div class="relative pt-6 px-4 sm:px-6 lg:px-8"></div>
      </div>

      <div class="mt-2 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
        <div class="sm:text-center lg:text-left">
          <h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
            <span class="block xl:inline">Chris Clifton</span>
            <span class="block text-indigo-600 xl:inline">Software Engineer</span>
          </h1>

          <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0"><span class="pr-2">👋</span>Hi, I'm Chris.</p>
          <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">I specialize in modern full-stack Ruby on Rails development.</p>
          <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">My current work is focused on designing and building applications in the cyber-security space but I'm always looking for a reason to run <code class="text-indigo-600">rails new</code>.</p>

          <div class="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start">
            <div class="rounded-md shadow">
              <%= link_to 'Contact', home_contact_path, class: "w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 md:py-4 md:text-lg md:px-10" %>
            </div>
            <div class="mt-3 sm:mt-0 sm:ml-3">
              <%= link_to 'Resume', resume_path, class: "w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-indigo-600 bg-indigo-100 hover:bg-indigo-200 md:py-4 md:text-lg md:px-10" %>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

  <div class="lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
    <%= image_tag "profile_pic.jpg", class: "h-56 w-full object-cover sm:h-72 md:h-96 lg:w-full lg:h-full" %>
  </div>
</div>

app/views/home/resume.html.erb
<div class="mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 lg:px-8">
  <div class="md:flex md:justify-between">
    <div></div>

    <div class="sm:flex sm:justify-center md:justify-start">
      <div class="mt-3 sm:mt-0 sm:ml-3">
        <div data-controller="resume" data-resume-url-value="<%= home_download_resume_path %>">
          <div id="download-pdf-button" data-action="click->resume#download" class="cursor-pointer flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-indigo-600 bg-indigo-100 hover:bg-indigo-200 md:py-4 md:text-lg md:px-10">
            Download PDF
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="md:hidden my-4 text-gray-500">
    I know, I know...here I am saying that this website is 100% responsive meanwhile I have some funky word breaks in this view on mobile.
    <br/><br/>
    I wanted to dynamically generate PDFs based on the contents of this view (rather than serve a static file) so I have chosen to allow some less-than-ideal formatting on mobile in order to preserve the styling of the PDF. 
  </div>

  <%= render partial: 'resume_body' %>
</div>

app/views/layouts/_nav.html.erb
<nav data-controller="nav" class="bg-white border-b border-gray-200">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between h-16">
      <div class="flex">
        <div class="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
          <%= link_to 'chrisclifton.dev', root_path, class: "#{active_nav('home', action_name, controller_name)}" %>
          <%= link_to 'Projects', projects_path, class: "#{active_nav('projects', action_name, controller_name)}" %>
          <%= link_to 'Blog', blog_path, class: "#{active_nav('posts', action_name, controller_name)}" %>
          <%= link_to 'Resume', resume_path, class: "#{active_nav('resume', action_name, controller_name)}" %>
          <% if current_user %>
            <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: 'nav-element' %>
          <% end %>
        </div>
      </div>

      <!-- Mobile menu -->
      <div class="-mr-2 flex items-center sm:hidden">
        <%= link_to 'chrisclifton.dev', root_path, class: "pr-4" %>
        <!-- Mobile menu button -->
        <button data-target="mobile-menu-hamburger" data-action="click->nav#toggleMobileMenu" type="button" class="bg-white inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!--
            Heroicon name: outline/menu

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6 text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!--
            Heroicon name: outline/x

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div data-target="nav.mobileMenu" class="hidden sm:hidden" id="mobile-menu">
    <div class="pt-2 pb-3 space-y-1">
      <%= link_to 'Projects', projects_path, class: "#{active_mobile_nav('projects', action_name, controller_name)}" %>
      <%= link_to 'Blog', blog_path, class: "#{active_mobile_nav('posts', action_name, controller_name)}" %>
      <%= link_to 'Resume', resume_path, class: "#{active_mobile_nav('resume', action_name, controller_name)}" %>
      <% if current_user %>
        <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: 'mobile-nav-element' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/posts/_likes.html.erb
<%= turbo_frame_tag "#{dom_id(post)}_likes" do %>
  <div id="like-button" data-controller="likes" class="flex">
    <%= form_with url: like_post_path(@post),
                  data: { action: 'click->likes#fire' },
                  method: 'PATCH' do |form| %>
      <%= image_submit_tag("thumbs_up.svg", width: "25", height: "25") %>
    <% end %>

    <%= post.likes.size %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<div class="mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 lg:px-8">
  <div class="flex justify-between items-center mb-8">
    <h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
      <span class="block xl:inline text-indigo-600">Posts</span>
    </h1>
    <% if current_user && current_user.admin? %>
      <%= link_to 'New post', new_post_path, class: "flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 md:py-4 md:text-lg md:px-10" %>
    <% end %>
  </div>

  <div class="w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="pt-2 pb-4">
      <%= form_with(url: posts_path, method: "GET", data: { controller: "form-submission", turbo_frame: "posts", turbo_action: "advance" }) do |form|%>
        <%= form.text_field :query, placeholder: 'Search', class: 'input', data: { action: "input->form-submission#search" } %>
      <% end %>
    </div>

    <%= render "posts", posts: @posts %>

    <div class="text-gray-500 font-medium p-2 block">
      <div class="text-center text-sm w-1/2 mx-auto">
        This feature is powered by Hotwire and Turbo. See <span class="text-indigo-600">my guide</span> for instructions on how you can build the same!
      </div>
      <a href="https://hotwired.dev/">
        <%= image_tag 'hotwire_logo.jpg', class: "p-2 w-1/2 max-w-xs mx-auto" %>
      </a>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post %>

  <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<div id="<%= dom_id @post %>" class="mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 lg:px-8">
  <div class="text-left">
    <%= link_to 'Back to posts', posts_path, class: "text-indigo-600 font-medium" %>

    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="my-4 md:w-3/4">
      <div data-controller="rich-text" class="text-gray-900">
        <p class="font-bold text-3xl mb-2">
          <%= @post.title %>
        </p>

        <p class="text-xl mb-2">
          <%= @post.heading %>
        </p>

        <p class="text-sm text-gray-500 italic">
          Published: <%= time_tag @post.created_at %> - Updated: <%= time_tag @post.updated_at %>
        </p>

        <p class="my-4">
          <%= @post.content %>
        </p>

        <div class="flex justify-between my-8">
          <%= link_to 'Back to posts', posts_path, class: "text-indigo-600 font-medium mb-4" %>
          <div class="text-sm text-gray-500 italic text-right">
            <p>Thanks for reading!</p>
            <p>- Chris</p>
          </div>
        </div>

        <div class="flex justify-between mb-8">
          <span></span>

          <div class="flex">
            <%= render partial: "likes", locals: { post: @post } %>
          </div>

          <div class="flex">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
            </svg>

            <%= turbo_frame_tag "comment_count" do %>
              <%= @post.comments.size %>
            <% end %>
          </div>

          <span></span>
        </div>

        <% if action_name != "show" %>
          <div class="mt-6">
            <%= link_to "Show this post", @post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
            <%= link_to 'Edit this post', edit_post_path(@post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %> 
          </div>

          <hr class="my-6">
        <% end %>
      </div>
    </div>

    <hr class="pb-4">

    <div class="pb-4">
      <%= render partial: "comments/form", locals: { comment: Comment.new } %>
    </div>

    <hr class="pb-8">

    <%= turbo_stream_from @post, :comments %>
    <div id="<%= "#{dom_id(@post)}_comments" %>" class="w-full md:w-3/4">
      <%= render @post.comments.order(created_at: :desc) %>
    </div>

    <% if current_user && current_user.admin? %>
      <%= link_to 'Edit this post', edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 lg:px-8">
  <div class="text-left">
    <h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
      <span class="block xl:inline text-indigo-600">Projects</span>
    </h1>

    <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg md:mt-5 md:text-xl lg:mx-0">
      Over the years, I have worked on a number of projects at work and at home- these are some of my favorites.
    </p>
  </div>

  <section class="pt-8">
    <div class="text-left mb-2">
      <h2 class="text-2xl tracking-tight font-extrabold text-gray-900">
        <span class="block xl:inline text-indigo-600">Personal</span>
      </h2>
    </div>

    <div class="text-gray-500 mb-4">
      Click on any of my personal projects for a closer look at the application and what I'm doing.
    </div>

    <%= link_to projects_chores_app_path do %>
      <div class="flex mb-8">
        <div class="mr-4 flex-shrink-0 self-center">
          <%= inline_svg_tag("the_house.svg", size: "64 * 64", class: "mx-auto") %>
        </div>
        <div>
          <h4 class="text-lg font-bold">The Chores App</h4>
          
          <p class="mt-1 text-gray-500">My current WIP side-project to track household tasks and responsibilities like chores and allowances, education and training, shopping lists, and more.</p>
        </div>
      </div>
    <% end %>


      <div class="flex mb-8">
        <div class="mr-3 flex-shrink-0 self-center">
          <span class="ml-2 text-6xl">🪴</span>
        </div>
        <div>
          <h4 class="text-lg font-bold">PiCU</h4>
          
          <p class="mt-1 text-gray-500">
            <span class="text-indigo-600">Project page under construction.</span><br/>
            Raspberry Pi "Plant ICU" to monitor soil moisture/temperature and deliver water based on the plant's needs and display the plant's overall health/reporting on an integrated touchscreen Rails application.
          </p>
        </div>
      </div>


    <%= link_to projects_christmas_bomb_path do %>
      <div class="flex mb-8">
        <div class="mr-3 flex-shrink-0 self-center">
        <span class="ml-2 text-6xl">💣</span>
      </div>
      <div>
          <h4 class="text-lg font-bold">The Christmas Bomb</h4>
          
        <p class="mt-1 text-gray-500">A spooky Christmas trivia game.</p>
      </div>
    </div>
    <% end %>

    <%= link_to projects_portfolio_path do %>
      <div class="flex mb-8">
        <div class="mr-3 flex-shrink-0 self-center">
          <span class="ml-2 text-6xl">🗂</span>
        </div>
        <div>
          <h4 class="text-lg font-bold">This Portfolio!</h4>
          
          <p class="mt-1 text-gray-500">Theres a bit more than static HTML on this website- take a tour of what all I'm doing here and how I decided to do it.</p>
        </div>
      </div>
    <% end %>


      <div class="flex mb-8">
        <div class="mr-3 flex-shrink-0 self-center">
        <span class="ml-2 text-6xl">🪞</span>
      </div>
      <div>
        <h4 class="text-lg font-bold">Vision</h4>
          
        <p class="mt-1 text-gray-500">
          <span class="text-indigo-600">Project page under construction.</span><br/>
          Raspberry Pi-powered smart mirror to display general day-to-day information like a clock, calendar, weather, etc.
        </p>
      </div>
    </div>

  </section>

  <section class="">
    <div class="text-left mb-2">
      <h2 class="text-2xl tracking-tight font-extrabold text-gray-900">
        <span class="block xl:inline text-indigo-600">Work</span>
      </h2>
    </div>

    <div class="text-gray-500 mb-4">
      Unfortunately, due to NDAs and all that, I can't get into the nitty gritty for these projects, but these are the high-level details of some of the things I do at work.
    </div>

    <div class="flex mb-8">
      <div class="mr-4 flex-shrink-0 self-center">
        <%= image_tag 'github.png' %>
      </div>
      <div>
        <h4 class="text-lg font-bold">GitHub Scanner</h4>
        
        <p class="mt-1 text-gray-500">Monitor every event on all +128 million public GitHub repositories and extract actionable vulnerability and cyber-security information.</p>
      </div>
    </div>

    <div class="flex mb-8">
      <div class="mr-4 flex-shrink-0 self-center">
        <%= image_tag "twitter.png", size: "64x64" %>
      </div>
      <div>
        <h4 class="text-lg font-bold">Twitter Parser</h4>
        
        <p class="mt-1 text-gray-500">Detect cyber-security "chatter" in Tweets (in real-time), match the chatter with known vulnerabilities, and calculate a proprietary "social risk score".</p>
      </div>
    </div>

    <div class="flex mb-8">
      <div class="mr-3 flex-shrink-0 self-center">
        <span class="ml-2 text-6xl">💽</span>
      </div>
      <div>
        <h4 class="text-lg font-bold">Data Ingestion System</h4>
        
        <p class="mt-1 text-gray-500">Vulnerability database management system for cyber-security researchers to collect, organize, and distribute cyber threat intelligence.</p>
      </div>
    </div>

    <div class="flex mb-8">
      <div class="mr-3 flex-shrink-0 self-center">
        <span class="ml-2 text-6xl">💻</span>
      </div>
      <div>
        <h4 class="text-lg font-bold">The Portal</h4>
        
        <p class="mt-1 text-gray-500">A client portal for the Data Ingestion System where users and organizations can input information on their hardware/software and receive vulnerability updates on them.</p>
      </div>
    </div>
  </section>
</div>